In [1]:
from sklearn.feature_extraction.text import CountVectorizer

# Example corpus
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?']

# Create the BoW model
vectorizer = CountVectorizer()

# Learn a vocabulary dictionary of all tokens in the raw documents
X = vectorizer.fit_transform(corpus)

# Summarize
print(vectorizer.get_feature_names_out())
print(X.toarray()) 

# Output
# ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
# [[0 1 1 1 0 0 1 0 1]
#  [0 2 0 1 0 1 1 0 1]
#  [1 0 0 1 1 0 1 1 1]
#  [0 1 1 1 0 0 1 0 1]]


['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

# create a corpus of sentences
corpus = [
    'The sky is blue and beautiful.',
    'Love this blue and beautiful sky!',
    'The quick brown fox jumps over the lazy dog.',
    'The brown fox is quick and the blue dog is lazy.',
    'The sky is very blue and the sky is very beautiful today.',
    'The dog is lazy but the brown fox is quick.'
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

# print the tf-idf values
print(X.toarray()) 

# print the feature names
print(vectorizer.get_feature_names_out())


[[0.39315931 0.458803   0.39315931 0.         0.         0.
  0.         0.39315931 0.         0.         0.         0.
  0.         0.458803   0.33952451 0.         0.         0.        ]
 [0.30999542 0.36175368 0.30999542 0.         0.         0.
  0.         0.         0.         0.         0.52252953 0.
  0.         0.36175368 0.         0.52252953 0.         0.        ]
 [0.         0.         0.         0.29665213 0.         0.29665213
  0.29665213 0.         0.42849459 0.29665213 0.         0.42849459
  0.29665213 0.         0.43905847 0.         0.         0.        ]
 [0.25164011 0.         0.25164011 0.2936551  0.         0.2936551
  0.2936551  0.50328023 0.         0.2936551  0.         0.
  0.2936551  0.         0.43462273 0.         0.         0.        ]
 [0.182579   0.21306323 0.182579   0.         0.         0.
  0.         0.365158   0.         0.         0.         0.
  0.         0.42612646 0.31534314 0.         0.3077559  0.61551179]
 [0.         0.         0.      

In [11]:
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained("bert-base-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)


In [12]:
from transformers import BertTokenizer, BertForMaskedLM
import torch


tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')
text = ("Napoleon revolutionised military organisation"
"Napoleon has legacy"
"Legacy still lives"
)
rep = tokenizer(text, return_tensors = "pt")
print("Before Masking",rep.input_ids)
rand = torch.rand(rep.input_ids.shape)
mask_arr = (rand < 0.15) * (rep.input_ids != 101) * (rep.input_ids != 102)
selection = torch.flatten(mask_arr[0].nonzero()).tolist()
rep.input_ids[0, selection] = 103
after_masking = rep.input_ids
print("After Masking", after_masking)


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Before Masking tensor([[  101,  8891,  4329,  5084,  2510,  5502,  2532, 15049,  2239,  2038,
          8027, 23115, 15719,  2145,  3268,   102]])
After Masking tensor([[  101,  8891,  4329,  5084,  2510,  5502,  2532, 15049,  2239,  2038,
          8027, 23115, 15719,  2145,  3268,   102]])
